/** Study areas imported from NDA_Emerging_Provider_Summary.xlsx (columns A–B). */
export const EMERGING_INTEREST_AREAS_BY_SLUG: Readonly<Record<string, readonly string[]>> = {
  'academies-australasia-polytechnic': ['Cookery', 'Hospitality', 'IT', 'Business'],
  'acap-university-college': ['Psychology', 'Counselling', 'Social Work', 'Coaching', 'Law'],
  'adelaide-central-school-of-art': ['Visual Art'],
  'adelaide-university': [
    'Business & Law',
    'Creative Arts',
    'Education & Social Sciences',
    'Engineering & IT',
    'Health',
    'Science',
  ],
  'alphacrucis-university-college': [
    'Ministry',
    'Theology',
    'Chaplaincy',
    'Christian Education',
    'Counselling',
    'Community Services',
  ],
  'asia-pacific-international-college-apic': ['Business', 'IT', 'Project Management'],
  'australian-catholic-university-acu': [
    'Health Sciences',
    'Education & Arts',
    'Law & Business',
    'Theology & Philosophy',
    'Nursing',
    'Psychology',
  ],
  'australian-chiropractic-college-acc': ['Chiropractic'],
  'australian-college-of-christian-studies-accs': [
    'Ministry',
    'Theology',
    'Education',
    'Christian Counselling',
  ],
  'australian-institute-of-higher-education-aih': [
    'Business',
    'Accounting',
    'IT',
    'Hospitality & Tourism',
    'Project Management',
  ],
  'asa-institute-of-higher-education': [
    'Accounting',
    'IT (AI, Cyber Security, Software Development)',
    'Project Management',
  ],
  'australian-university-college-of-divinity-aucd': ['Theology', 'Ministry'],
  'australian-university-of-theology-aut': ['Theology', 'Ministry', 'Pastoral Care'],
  'avondale-university': [
    'Nursing',
    'Teaching/Education',
    'Business',
    'Ministry & Theology',
    'Arts',
    'Counselling',
    'Lifestyle Medicine',
  ],
  'bpp-institute': [
    'Accounting',
    'Management',
    'Marketing (UG); MBA',
    'Management Information Systems (PG)',
  ],
  'campion-college-australia': ['Liberal Arts — History', 'Literature', 'Philosophy', 'Theology'],
  'chisholm-institute': [
    'Trades',
    'Health',
    'IT',
    'Business',
    'Hospitality (VET + Higher Education)',
  ],
  'christian-heritage-college-chc': [
    'Business',
    'Education',
    'Arts & Humanities',
    'Ministries',
    'Behavioural/Social Sciences',
  ],
  'curtin-college': ['Diploma pathway (general pathway into Curtin University degrees)'],
  'deakin-university': ['Broad — comprehensive university (specific list not detailed in profile)'],
  'edith-cowan-college-ecc': [
    'Diploma pathway (general pathway into ECU degrees); Foundation Program',
    'English-language courses',
  ],
  'edith-cowan-university-ecu': [
    'Broad — comprehensive university (specific list not detailed in profile)',
  ],
  'engineering-institute-of-technology-eit': [
    'Civil',
    'Electrical',
    'Mechanical',
    'Industrial Automation',
    'Renewable Energy Engineering',
  ],
  'equals-international': [
    'Nursing & Health',
    'Social Work & Community',
    'Trades & Applied Technologies',
    'Ayurveda/Integrative Health',
    'Business Leadership & Management',
  ],
  'excelsia-university-college': [
    'Business',
    'Counselling',
    'Creative & Performing Arts',
    'Education',
    'Social Work',
  ],
  'federation-university-australia': [
    'Broad — co-operative university model (specific list not detailed in profile)',
  ],
  'griffith-college': ['Diploma pathway (general pathway into Griffith University degrees)'],
  'holmes-institute': [
    'Business',
    'Accounting & Finance',
    'Aviation',
    'Cybersecurity',
    'Fashion',
    'Education & Teaching',
    'Information Systems & Technology',
  ],
  'international-college-of-management-sydney-icms': [
    'Business',
    'Event Management',
    'Hospitality',
    'Property',
    'IT',
  ],
  'jmc-academy': [
    'Music',
    'Audio',
    'Film & TV Production',
    'Acting',
    'Animation',
    'Design',
    'Game Design',
    'Entertainment Business Management',
  ],
  'kaplan-business-school-kbs': ['Business', 'IT', 'Accounting', 'Hospitality & Tourism'],
  'king-s-own-institute-koi': ['Business', 'Accounting', 'IT', 'TESOL'],
  'la-trobe-college-australia': [
    'Diploma pathway into La Trobe University',
    'incl. Cybersecurity and Business Analytics',
  ],
  'leaders-institute': ['Business', 'Agribusiness'],
  'lyons-college': [
    'Business',
    'Accounting',
    'IT',
    'Hospitality',
    'Project Management',
    'Leadership & Management',
  ],
  'marcus-oldham-college': ['Agribusiness', 'Agricultural Business Management', 'Farm Management'],
  'melbourne-polytechnic': [
    'Trades',
    'Agriculture',
    'Animal Studies',
    'IT',
    'Hospitality',
    'Creative fields (VET + Higher Education)',
  ],
  'moore-theological-college': ['Theology', 'Christian Ministry'],
  'murdoch-university': [
    'Veterinary Science',
    'Agricultural Science',
    'Allied Health + 200+ courses broadly',
  ],
  'psc-creative-college': ['Photography', 'Screen Media', 'Design', 'Creative Industries'],
  'polytechnic-institute-australia-pia': ['Business', 'ICT'],
  'sheridan-institute-of-higher-education': ['Business/Management; Science pathway'],
  'stanley-college': [
    'Business',
    'Nursing',
    'Health',
    'Early Childhood Education',
    'Hospitality',
    'Commercial Cookery',
    'ICT',
  ],
  'tabor-college': [
    'Teacher Education',
    'Humanities',
    'TESOL',
    'Counselling',
    'Youth Work',
    'Ministry',
    'Theology',
    'Music',
  ],
  'tafe-nsw': [
    'Accounting & Finance',
    'Business & Marketing',
    'Education & Training',
    'Engineering',
    'ICT',
    'Fashion',
    'Screen/Media/Games',
    'and more',
  ],
  'universal-business-school-sydney-ubss': ['Business', 'Accounting', 'MBA'],
  'university-of-divinity': [
    'Theology',
    'Ministry',
    'Clinical Pastoral Education',
    'Christian Counselling',
    'Indigenous Theology',
  ],
  'university-of-technology-sydney-uts': [
    'Broad — large research university (specific list not detailed in profile)',
  ],
  'university-of-the-sunshine-coast-unisc': [
    'Nursing',
    'Engineering',
    'Paramedicine + broad program range',
  ],
  'university-of-wollongong-uow': [
    'Broad — large research university (specific list not detailed in profile)',
  ],
  'uow-college-australia': [
    'Business',
    'Engineering',
    'IT',
    'Nursing',
    'Medical & Health Sciences (pathway)',
  ],
  'victoria-university-vu': [
    'Arts/Humanities/Community Services',
    'Business',
    'IT/Cyber/Data Science',
    'Education',
    'Engineering/Science/Built Environment',
    'Health/Biomedicine/Nursing',
    'Hospitality/Tourism/Events',
    'Law/Justice',
    'Sports/Exercise',
    'Sustainability',
    'Trades',
  ],
  'william-angliss-institute': ['Foods', 'Tourism', 'Hospitality', 'Hotel Management', 'Events'],
};
